"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Lang = 'EN' | 'ES' | 'CA' | 'DE' | 'FR' | 'NL';

interface LangContextArgs {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    'nav.events': 'Events', 'nav.map': 'The Map', 'nav.guide': 'The Guide', 'nav.news': 'News', 'nav.about': 'Contact',
    'news.today': 'LATEST FROM THE STREET',
    'hero.title1': 'Experience ', 'hero.title2': 'Like a Local',
    'hero.subtitle': 'The automated hub for international residents. Unbiased events, secret maps, and the raw truth on surviving the city.',
    'hero.btn1': 'BROWSE EVENTS', 'hero.btn2': 'EXPLORE BEER MAP',
    'feat.event.title': 'The Pulse', 'feat.event.desc': 'Curated high-signal events and live feeds of what\'s actually happening.',
    'feat.map.title': 'The Beer Map', 'feat.map.desc': 'The definitive guide to terrace pricing and local haunts across the city.',
    'feat.guide.title': 'Practical Guides', 'feat.guide.desc': 'Everything you actually need to know: from NIE hacks to finding a decent flat.',
    'footer.desc': 'The platform for those of us who live here. No fluff, just high-signal info.',
    'footer.platform': 'Platform', 'footer.contact': 'Contact', 'footer.rights': 'All rights reserved.',
    'events.title1': 'The Pulse of ', 'events.title2': 'Barcelona',
    'events.subtitle': 'Curated Gems & Local Secrets',
    'events.desc': 'Aggregated in real-time from 50+ high-signal sources including RA, Timeout, and the City Council.',
    'events.category.Music': 'Music', 'events.category.Art': 'Art', 'events.category.Festival': 'Festival', 'events.category.Free': 'Free', 'events.category.Opening': 'Opening', 'events.category.Other': 'Other',
    'events.calendar.title': 'The Agenda', 'events.venue': 'Venue', 'events.tickets': 'Tickets/Info', 'events.search': 'Search the pulse...',
    'map.filter.title': 'Filters:', 'map.filter.neighborhood': 'Neighborhood', 'map.filter.budget': 'Budget (0.5L Beer)',
    'map.filter.facilities': 'International Essentials', 'map.filter.terrace': 'Sunny Terrace', 'map.filter.sports': 'Live Sports',
    'map.filter.availability': 'Availability', 'map.filter.open': 'Open Now', 'map.filter.top_rated': 'Local Favorites (4.5+ ★)',
    'map.filter.walking_dist': 'Walking distance', 'map.loc.find_me': 'Find me', 'map.loc.mins': 'mins',
    'map.search.placeholder': 'Search local haunts...', 'map.results.count': 'results', 'map.venue.beer': 'Beer (0.5L)',
    'map.venue.no_photo': 'No Photo', 'map.venue.open_badge': 'OPEN', 'map.venue.tag.cheap': 'Low prices',
    'map.venue.loading': 'Fetching street data...', 'map.venue.empty': 'Dead end. Try another neighborhood.', 'map.venue.reset': 'Reset Filters',
    'map.report_price': 'Report Price', 'map.directions': 'Get Directions', 'map.sun_timeline': 'Terrace Sun', 'map.verified': 'verified', 'map.confidence.low': 'No price data yet', 'map.history': 'Price History',
    'map.form.type': 'Beer Type', 'map.form.size': 'Size', 'map.form.price': 'Price (€)', 'map.form.submit': 'Submit Price',
    'review.1': 'The Beer Map saved my wallet in Gòtic. Absolute genius.',
    'review.2': 'Finally, an agenda that includes the proper neighborhood festivals.',
    'review.3': 'The NIE guide is the only reason I wasn\'t deported. Lifesaver.',
    'review.4': 'Zero bias, fully automated. The benchmark for BCN residents.',
    'review.5': 'I use the transit guide daily. T-Mobilitat explained for humans.',
    'guide.title1': 'Street ', 'guide.title2': 'Guides',
    'guide.desc': 'Step-by-step instructions for navigating the bureaucracy and logistics without the drama.',
    'guide.nie': 'Get your NIE without losing your mind.',
    'guide.house': 'Find a room or flat in the right neighborhood.',
    'guide.trans': 'Master the metro, the bus, and T-Mobilitat.',
    'guide.read': 'READ THE INTEL →',
    'guide.back': 'Back to Guides',
    'guide.nie.title': 'NIE Registration',
    'guide.nie.desc': 'The NIE is the holy grail of living here. You need it for everything.',
    'guide.nie.step1': 'The Cita Previa Hunt',
    'guide.nie.step1_desc': 'The hardest part. We track official slots in real-time.',
    'guide.nie.btn_cita': 'See Official Slots',
    'guide.nie.step2': 'EX-15 Paperwork',
    'guide.nie.step2_desc': 'Fill it in perfectly. "Work" or "Social Interest" usually clears.',
    'guide.nie.btn_ex15': 'Download EX-15',
    'guide.nie.step3': 'The Tasa Fee (790-012)',
    'guide.nie.step3_desc': 'Pay the fee at any ATM before your slot. Don\'t forget the receipt.',
    'guide.nie.btn_tasa': 'Form 790-012',
    'guide.nie.step4': 'The Face-to-Face',
    'guide.nie.step4_desc': '2 copies of everything. Passport. Receipt. And a smile.',
    'guide.house.title': 'Housing & Rent',
    'guide.house.desc': 'The market moves fast. Here\'s how to stay one step ahead.',
    'guide.house.step1': 'Pick Your Barrio',
    'guide.house.step1_desc': 'Gràcia for vibes, Eixample for order, Poble Sec for local haunt.',
    'guide.house.step2': 'The Pro Tools',
    'guide.house.step2_desc': 'Idealista for flats, Badi for rooms. Be aggressive.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'The Paper Intel',
    'guide.house.step3_desc': 'Contract, payslips, NIE. Have them ready as a single PDF.',
    'guide.house.step4': 'No Money Upfront',
    'guide.house.step4_desc': 'Scams are real. Not a cent until the keys are in your hand.',
    'home.news.title': 'THE INSIDER BRIEFING',
    'home.news.desc': 'The Sunday recap of everything that actually happened in the city.',
    'home.news.placeholder': 'Your email address',
    'home.news.btn': 'GET THE INTEL',
    'home.contact.title': 'CONNECT',
    'home.contact.desc': 'Got a tip? A partnership? We respond in 24 hours.',
    'home.contact.name': 'Your Name',
    'home.contact.email': 'Email Address',
    'home.contact.msg': 'What\'s on your mind?',
    'home.contact.btn': 'SEND',
    'guide.trans.title': 'Transit Intel',
    'guide.trans.desc': 'One of the best networks in Europe, if you know which lines to dodge.',
    'guide.trans.step1': 'Digital T-Mobilitat',
    'guide.trans.step1_desc': 'Forget the paper card. Go digital via the app.',
    'guide.trans.btn_app': 'Get T-Mobilitat',
    'guide.trans.step2': 'T-Usual Rules',
    'guide.trans.step2_desc': 'Unlimited rides. If you live here, it\'s the only card you need.',
    'guide.trans.step3': 'Eyes on Your Gear',
    'guide.trans.step3_desc': 'L3 and L4 are prime areas for pickpockets. Bag in front.',
    'guide.trans.step4': 'Metro Intel',
    'guide.trans.step4_desc': 'Offline maps for when you drop signal underground.',
    'guide.trans.btn_map': 'Download Map',
    'guide.empadronamiento.title': 'The Padrón',
    'guide.empadronamiento.desc': 'City Hall registration. Essential for healthcare and bureaucracy.',
    'guide.sim.title': 'SIM & Data',
    'guide.sim.desc': 'Total connectivity. The best local networks for nomads.',
    'guide.insurance.title': 'Health Intel',
    'guide.insurance.desc': 'CatSalut vs Private. How to see a doctor without the wait.',
    'guide.bank.title': 'Banking hacks',
    'guide.bank.desc': 'IBANs and how to avoid the maintenance fee trap.',
    'guide.health.title': 'Healthcare System',
    'guide.health.desc': 'Locate your CAP and dominate the online portals.',
    'guide.empadronamiento.step1': 'Book Your OAC', 'guide.empadronamiento.step1_desc': 'Request a slot at your nearest city hall office.',
    'guide.empadronamiento.step2': 'The Contract', 'guide.empadronamiento.step2_desc': 'You need a rental contract for 6+ months.',
    'guide.empadronamiento.step3': 'The Volante', 'guide.empadronamiento.step3_desc': 'Walk out with your residency proof instantly.',
    'guide.sim.step1': 'Pick a Network', 'guide.sim.step1_desc': 'Digi for value; Orange or Vodafone for 5G speed.',
    'guide.sim.step2': 'Prepaid First', 'guide.sim.step2_desc': 'Grab a prepaid SIM with just your passport while you wait for your NIE.',
    'guide.sim.step3': 'Locutorios', 'guide.sim.step3_desc': 'The secret to instant activation in any neighborhood.',
    'guide.insurance.step1': 'CatSalut (Public)', 'guide.insurance.step1_desc': 'Free. Requires Padrón and a Social Security number.',
    'guide.insurance.step2': 'Private (Adeslas/Sanitas)', 'guide.insurance.step2_desc': 'Crucial for fast specialist access and residency visas.',
    'guide.insurance.step3': 'Zero Co-pays', 'guide.insurance.step3_desc': 'A "Sin Copagos" clause is mandatory for most visa applications.',
    'guide.bank.step1': 'Digital Neo-Banks', 'guide.bank.step1_desc': 'N26 and Revolut give you a Spanish IBAN with just a passport.',
    'guide.bank.step2': 'Traditional Giants', 'guide.bank.step2_desc': 'Santander or BBVA. Better if you plan on getting a mortgage.',
    'guide.bank.step3': 'The Fee Trap', 'guide.bank.step3_desc': 'Always ask for a "Cuenta Sin Comisiones". Don\'t pay for basics.',
    'guide.health.step1': 'Find Your CAP', 'guide.health.step1_desc': 'Each neighborhood has its own health center. Locate yours.',
    'guide.health.step2': 'Get Your TSI', 'guide.health.step2_desc': 'Bring your Padrón to the CAP to get your physical card.',
    'guide.health.step3': 'La Meva Salut App', 'guide.health.step3_desc': 'The online portal for prescriptions and fast appointments.',
    'cookie.title': 'Privacy & Coffee', 'cookie.desc': 'We use cookies to keep the lights on. Essentials stay, the rest are optional.', 
    'cookie.accept': 'Accept All', 'cookie.decline': 'Essentials Only',
    'news.success': 'You\'re in. Welcome to the circle.', 'news.error.exists': 'You\'re already on the list.', 'news.error.invalid': 'That email doesn\'t look right.', 'news.error.generic': 'Servers are taking a siesta. Try later.', 'news.error.server_error': 'Database is down. We\'re on it.',
    'news.unsub.success': 'Unsubscribed. See you around.',
    'home.hero.title': 'BCN. RIGHT NOW.',
    'home.hero.subtitle': 'Events · Cheap beers · Local news · Expat guides — updated daily.',
    'home.hero.cta_events': "What's on tonight →",
    'home.hero.cta_beers': "Find cheap beer →",
    'home.bcn_today': 'BCN TODAY',
    'home.more_news': 'More news →',
    'home.sunday_briefing': 'THE SUNDAY BRIEFING',
    'home.sunday_desc': 'Every Sunday. The week in BCN, condensed.',
    'home.subscribe': 'Subscribe',
    'home.join_count': 'Join 1,200+ internationals in the loop',
    'map.per_half_litre': 'per 0.5L draught',
    'map.reviews': 'reviews',
    'map.verified_price': 'Verified price',
    'map.verified_desc': 'Updated recently by users',
    'map.features': 'Features',
    'map.feature.terrace': 'Terrace Area',
    'map.feature.sports': 'Sports Screen',
    'map.feature.rooftop': 'Rooftop View',
    'map.sun_outlook': 'Sun Outlook',
    'map.get_directions': 'Get Directions',
    'map.update_price': 'Update'
  },
  ES: {
    'nav.events': 'Eventos', 'nav.map': 'El Mapa', 'nav.guide': 'La Guía', 'nav.news': 'Noticias', 'nav.about': 'Contacto',
    'news.today': 'LO ÚLTIMO DE LA CALLE',
    'hero.title1': 'Vive Barcelona ', 'hero.title2': 'Como un Barcelonés.',
    'hero.subtitle': 'Tu acceso sin filtros al pulso de la ciudad. Eventos, el mapa definitivo de cañas y cómo sobrevivir a la burocracia sin perder la cabeza.',
    'hero.btn1': 'QUÉ SE CUECE', 'hero.btn2': 'MAPA DE CAÑAS',
    'feat.event.title': 'Pulsaciones', 'feat.event.desc': 'Eventos seleccionados y feeds en directo de lo que realmente importa en la ciudad.',
    'feat.map.title': 'Mapa de Cañas', 'feat.map.desc': 'La guía definitiva de precios de terrazas y locales auténticos en cada barrio.',
    'feat.guide.title': 'Guías de Supervivencia', 'feat.guide.desc': 'Todo lo que realmente necesitas saber: desde el NIE hasta cómo encontrar piso.',
    'footer.desc': 'La plataforma para los que vivimos aquí. Sin rollos, solo la mejor información.',
    'footer.platform': 'Plataforma', 'footer.contact': 'Contacto', 'footer.rights': 'Todos los derechos reservados.',
    'events.title1': 'El Pulso de ', 'events.title2': 'Barcelona',
    'events.subtitle': 'Joyas Curadas y Secretos de Barrio',
    'events.desc': 'Datos agregados de más de 50 fuentes: desde RA y Timeout hasta los feeds del Ayuntamiento.',
    'events.category.Music': 'Música', 'events.category.Art': 'Arte', 'events.category.Festival': 'Festival', 'events.category.Free': 'Gratis', 'events.category.Opening': 'Apertura', 'events.category.Other': 'Otros',
    'events.calendar.title': 'La Agenda', 'events.venue': 'Sitio', 'events.tickets': 'Info', 'events.search': 'Busca tu plan...',
    'map.filter.title': 'Filtros:', 'map.filter.neighborhood': 'Barrio', 'map.filter.budget': 'Tu presupuesto (Caña 0.5L)',
    'map.filter.facilities': 'Básicos para internacionales', 'map.filter.terrace': 'Terraza con Sol', 'map.filter.sports': 'Fútbol en Directo',
    'map.filter.availability': 'Disponibilidad', 'map.filter.open': 'Abierto Ya', 'map.filter.top_rated': 'Favoritos del Barrio (4.5+ ★)',
    'map.filter.walking_dist': 'Distancia a pie', 'map.loc.find_me': 'Búscame', 'map.loc.mins': 'min',
    'map.search.placeholder': 'Busca bar por nombre...', 'map.results.count': 'resultados', 'map.venue.beer': 'Caña (0.5L)',
    'map.venue.no_photo': 'Sin Foto', 'map.venue.open_badge': 'ABIERTO', 'map.venue.tag.cheap': 'Caña barata',
    'map.venue.loading': 'Cargando datos de la calle...', 'map.venue.empty': 'No hay nada aquí. Prueba otro barrio.', 'map.venue.reset': 'Resetear Filtros',
    'map.report_price': 'Informar precio', 'map.directions': 'Cómo llegar', 'map.sun_timeline': 'Sol en terraza', 'map.verified': 'verificado', 'map.confidence.low': 'Sin datos de precios', 'map.history': 'Historial',
    'map.form.type': 'Tipo de cerveza', 'map.form.size': 'Tamaño', 'map.form.price': 'Precio (€)', 'map.form.submit': 'Enviar precio',
    'review.1': '¡El mapa de cañas me salvó la cartera en el Gòtic! Es una genialidad.',
    'review.2': 'Por fin una agenda que incluye las fiestas mayores de los barrios.',
    'review.3': 'La guía del NIE es la única razón por la que no me han deportado.',
    'review.4': 'Sin sesgos, totalmente automático. Brutal para residentes internacionales.',
    'review.5': 'La guía de transporte me salva cada día. ¡La T-Mobilitat explicada fácil!',
    'guide.title1': 'Guías de ', 'guide.title2': 'Calle',
    'guide.desc': 'Instrucciones paso a paso para navegar la burocracia y la logística de la ciudad sin drama.',
    'guide.nie': 'Consigue tu NIE sin que te explote la cabeza.',
    'guide.house': 'Encuentra tu sitio en el barrio que te toque.',
    'guide.trans': 'Domina el metro, el bus y la T-Mobilitat.',
    'guide.read': 'LEER RESUMEN →',
    'guide.back': 'Volver a Guías',
    'guide.nie.title': 'Registro del NIE',
    'guide.nie.desc': 'El NIE es el santo grial para vivir aquí. Lo necesitas para absolutamente todo.',
    'guide.nie.step1': 'La Caza de la Cita Previa',
    'guide.nie.step1_desc': 'La parte más difícil. Nosotros miramos los huecos oficiales por ti.',
    'guide.nie.btn_cita': 'Ver Huecos Oficiales',
    'guide.nie.step2': 'El Formulario EX-15',
    'guide.nie.step2_desc': 'Rellénalo perfecto. Poner "Interés Social" o "Trabajo" suele funcionar.',
    'guide.nie.btn_ex15': 'Descargar EX-15',
    'guide.nie.step3': 'La Tasa (790-012)',
    'guide.nie.step3_desc': 'Paga los pocos euros que vale en un cajero antes de ir.',
    'guide.nie.btn_tasa': 'Formulario 790-012',
    'guide.nie.step4': 'El Cara a Cara',
    'guide.nie.step4_desc': '2 copias de todo. Pasaporte. Justificante de pago. Y una sonrisa.',
    'guide.house.title': 'Vivienda y Alquiler',
    'guide.house.desc': 'El mercado vuela. Aquí tienes cómo ir un paso por delante.',
    'guide.house.step1': 'Elige tu Barrio',
    'guide.house.step1_desc': 'Gràcia por el ambiente, Eixample por el orden, Poble Sec por las cañas.',
    'guide.house.step2': 'Usa las Herramientas Pro',
    'guide.house.step2_desc': 'Idealista para pisos, Badi para habitaciones. Sé rápido.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'Prepara el Papeleo',
    'guide.house.step3_desc': 'Contrato, nóminas, NIE. Tenlo todo en un PDF listo para enviar.',
    'guide.house.step4': 'No Pagues Sin Verlo',
    'guide.house.step4_desc': 'Las estafas existen. Ni un euro hasta que tengas las llaves.',
    'home.news.title': 'EL BOLETÍN DOMINICAL',
    'home.news.desc': 'El resumen de todo lo que realmente ha pasado en la ciudad esta semana.',
    'home.news.placeholder': 'Tu correo electrónico',
    'home.news.btn': 'RECIBIR EL BOLETÍN',
    'home.contact.title': 'CONECTA',
    'home.contact.desc': '¿Tienes un soplo? ¿Una idea? Respondemos en 24 horas.',
    'home.contact.name': 'Tu Nombre',
    'home.contact.email': 'Correo Electrónico',
    'home.contact.msg': '¿Qué tienes en mente?',
    'home.contact.btn': 'ENVIAR',
    'guide.trans.title': 'Guía de Tránsito',
    'guide.trans.desc': 'Una de las mejores redes de Europa, si sabes qué líneas evitar.',
    'guide.trans.step1': 'T-Mobilitat Digital',
    'guide.trans.step1_desc': 'Olvídate del papel. Pásate al digital con la app.',
    'guide.trans.btn_app': 'Bajar T-Mobilitat',
    'guide.trans.step2': 'La T-Usual manda',
    'guide.trans.step2_desc': 'Viajes ilimitados. Si vives aquí, es lo único que necesitas.',
    'guide.trans.step3': 'Ojo a tus cosas',
    'guide.trans.step3_desc': 'La L3 y L4 son territorio comanche para descuidados. Mochila delante.',
    'guide.trans.step4': 'Mapas del Metro',
    'guide.trans.step4_desc': 'Mapas offline para cuando te quedes sin cobertura abajo.',
    'guide.trans.btn_map': 'Descargar Mapa',
    'guide.empadronamiento.title': 'El Padrón',
    'guide.empadronamiento.desc': 'El registro municipal. Vital para la sanidad y la administración.',
    'guide.sim.title': 'SIM y Datos',
    'guide.sim.desc': 'Conectividad total. Las mejores redes locales para nómadas.',
    'guide.insurance.title': 'Seguro Médico',
    'guide.insurance.desc': 'CatSalut vs Privado. Cómo ir al médico sin esperas.',
    'guide.bank.title': 'Banca',
    'guide.bank.desc': 'IBANs y cómo evitar que te claven comisiones de mantenimiento.',
    'guide.health.title': 'El Hack de la Salud',
    'guide.health.desc': 'Encontrar tu CAP y dominar el portal online.',
    'guide.empadronamiento.step1': 'Reserva tu OAC', 'guide.empadronamiento.step1_desc': 'Pide cita en tu oficina de atención ciudadana más cercana.',
    'guide.empadronamiento.step2': 'El Contrato', 'guide.empadronamiento.step2_desc': 'Necesitas un contrato de alquiler de más de 6 meses.',
    'guide.empadronamiento.step3': 'El Volante', 'guide.empadronamiento.step3_desc': 'Sal con tu papel de residente al instante.',
    'guide.sim.step1': 'Elige Operador', 'guide.sim.step1_desc': 'Digi por precio; Orange o Vodafone por velocidad 5G.',
    'guide.sim.step2': 'Prepago Primero', 'guide.sim.step2_desc': 'Pilla una SIM de prepago solo con pasaporte mientras esperas el NIE.',
    'guide.sim.step3': 'Locutorios', 'guide.sim.step3_desc': 'El secreto para activación instantánea en cualquier barrio.',
    'guide.insurance.step1': 'CatSalut (Público)', 'guide.insurance.step1_desc': 'Gratis. Requiere Padrón y número de la seguridad social.',
    'guide.insurance.step2': 'Privado (Adeslas/Sanitas)', 'guide.insurance.step2_desc': 'Crucial para especialistas rápidos y visados de residencia.',
    'guide.insurance.step3': 'Sin Copagos', 'guide.insurance.step3_desc': 'La cláusula "Sin Copagos" es obligatoria para la mayoría de visados.',
    'guide.bank.step1': 'Neobancos Digitales', 'guide.bank.step1_desc': 'N26 y Revolut te dan IBAN español solo con el pasaporte.',
    'guide.bank.step2': 'Gigantes Tradicionales', 'guide.bank.step2_desc': 'Santander o BBVA. Mejores si buscas hipoteca más adelante.',
    'guide.bank.step3': 'La Trampa de las Comisiones', 'guide.bank.step3_desc': 'Pide siempre "Cuenta Sin Comisiones". No pagues por lo básico.',
    'guide.health.step1': 'Ubica tu CAP', 'guide.health.step1_desc': 'Cada barrio tiene su centro de salud. Encuentra el tuyo.',
    'guide.health.step2': 'Registra tu TSI', 'guide.health.step2_desc': 'Lleva tu padrón al CAP para que te den la tarjeta física.',
    'guide.health.step3': 'App La Meva Salut', 'guide.health.step3_desc': 'El portal online para recetas y citas rápidas.',
    'cookie.title': 'Privacidad y Café', 'cookie.desc': 'Usamos cookies para mantener esto en marcha. Las esenciales se quedan, el resto las puedes mandar a paseo.', 
    'cookie.accept': 'Aceptar Todo', 'cookie.decline': 'Solo Esenciales',
    'news.success': 'Ya estás dentro. Bienvenido al círculo.', 'news.error.exists': 'Ya estás en la lista, tío.', 'news.error.invalid': 'Ese correo no me cuadra.', 'news.error.generic': 'El servidor se ha ido de siesta. Prueba luego.', 'news.error.server_error': 'La base de datos está caída. Estamos en ello.',
    'news.unsub.success': 'Eliminado. ¡Nos vemos por ahí!',
    'home.hero.title': 'BARCELONA. AHORA.',
    'home.hero.subtitle': 'Eventos · Cervezas baratas · Noticias locales · Guías — actualizado a diario.',
    'home.hero.cta_events': "Qué se cuece hoy →",
    'home.hero.cta_beers': "Mapa de cañas →",
    'home.bcn_today': 'BCN HOY',
    'home.more_news': 'Más noticias →',
    'home.sunday_briefing': 'EL BOLETÍN DOMINICAL',
    'home.sunday_desc': 'Cada domingo. La semana en BCN, condensada.',
    'home.subscribe': 'Suscribirse',
    'home.join_count': 'Únete a más de 1.200 internacionales',
    'map.per_half_litre': 'por caña de 0.5L',
    'map.reviews': 'reseñas',
    'map.verified_price': 'Precio verificado',
    'map.verified_desc': 'Actualizado recientemente',
    'map.features': 'Características',
    'map.feature.terrace': 'Terraza',
    'map.feature.sports': 'Deportes',
    'map.feature.rooftop': 'Vistas Terraza',
    'map.sun_outlook': 'Pronóstico Sol',
    'map.get_directions': 'Cómo llegar',
    'map.update_price': 'Actualizar'
  },
  CA: {
    'nav.events': 'Esdeveniments', 'nav.map': 'El Mapa', 'nav.guide': 'La Guia', 'nav.news': 'Notícies', 'nav.about': 'Contacte',
    'news.today': "L'ÚLTIM DEL CARRER",
    'hero.title1': 'Viu Barcelona ', 'hero.title2': 'Com un Barceloní.',
    'hero.subtitle': 'Accés directe al pols de la ciutat. Agenda d\'esdeveniments, el mapa definitiu de canyes i com sobreviure a la burocràcia sense drama.',
    'hero.btn1': 'QUÈ ES COU', 'hero.btn2': 'MAPA DE CANYES',
    'feat.event.title': 'El Pols', 'feat.event.desc': 'Esdeveniments seleccionats i secrets locals de cada barri de la ciutat.',
    'feat.map.title': 'Mapa de Canyes', 'feat.map.desc': 'La guia definitiva de preus de terrasses i locals autèntics.',
    'feat.guide.title': 'Guies de Carrer', 'feat.guide.desc': 'Tot el que realment necessites saber sobre el NIE, habitatge i logística.',
    'footer.desc': 'La plataforma per a la gent que vivim aquí. Sense biaixos, només la millor informació.',
    'footer.platform': 'Plataforma', 'footer.contact': 'Contacte', 'footer.rights': 'Tots els drets reservats.',
    'events.title1': 'El Pols de ', 'events.title2': 'Barcelona',
    'events.subtitle': 'Pedres Precioses i Secrets Locals',
    'events.desc': 'Dades agregades de més de 50 fonts: des de RA i Timeout fins a l\'Ajuntament.',
    'events.category.Music': 'Música', 'events.category.Art': 'Art', 'events.category.Festival': 'Festival', 'events.category.Free': 'Gratis', 'events.category.Opening': 'Obertura', 'events.category.Other': 'Altres',
    'events.calendar.title': 'L\'Agenda', 'events.venue': 'Lloc', 'events.tickets': 'Info', 'events.search': 'Busca el teu pla...',
    'map.filter.title': 'Filtres:', 'map.filter.neighborhood': 'Barri', 'map.filter.budget': 'El teu pressupost (Canya 0.5L)',
    'map.filter.facilities': 'Bàsics per a internacionals', 'map.filter.terrace': 'Terrassa amb Sol', 'map.filter.sports': 'Futbol en Directe',
    'map.filter.availability': 'Disponibilitat', 'map.filter.open': 'Obert Ara', 'map.filter.top_rated': 'Preferits (4.5+ ★)',
    'map.filter.walking_dist': 'Distància a peu', 'map.loc.find_me': 'Troba\'m', 'map.loc.mins': 'min',
    'map.search.placeholder': 'Busca bar per nom...', 'map.results.count': 'resultats', 'map.venue.beer': 'Canya (0.5L)',
    'map.venue.no_photo': 'Sense Foto', 'map.venue.open_badge': 'OBERT', 'map.venue.tag.cheap': 'Canya barata',
    'map.venue.loading': 'Carregant dades del carrer...', 'map.venue.empty': 'No hi ha res aquí. Prova un altre barri.', 'map.venue.reset': 'Resetejar Filtres',
    'map.report_price': 'Informar preu', 'map.directions': 'Com arribar', 'map.sun_timeline': 'Sol a la terrassa', 'map.verified': 'verificat', 'map.confidence.low': 'Sense dades de preus', 'map.history': 'Historial',
    'map.form.type': 'Tipus de cervesa', 'map.form.size': 'Mida', 'map.form.price': 'Preu (€)', 'map.form.submit': 'Enviar preu',
    'review.1': 'El mapa de canyes va salvar la meva cartera al Gòtic! És una genialitat.',
    'review.2': 'Per fi un calendari que inclou les festes majors dels barris.',
    'review.3': 'La guia del NIE és l\'única raó per la qual encara sóc aquí.',
    'review.4': 'Sense biaixos, totalment automàtic. Brutal per residents internacionals.',
    'review.5': 'La guia de transport em salva cada dia. La T-Mobilitat explicada fàcil!',
    'guide.title1': 'Guies de ', 'guide.title2': 'Carrer',
    'guide.desc': 'Instruccions pas a pas per navegar la burocràcia i la logística de la ciutat sense drama.',
    'guide.nie': 'Aconsegueix el teu NIE sense que t\'exploti el cap.',
    'guide.house': 'Troba el teu lloc al barri que et toqui.',
    'guide.trans': 'Domina el metro, el bus i la T-Mobilitat.',
    'guide.read': 'LLEGIR RESUM →',
    'guide.back': 'Tornar a Guies',
    'guide.nie.title': 'Registre del NIE',
    'guide.nie.desc': 'El NIE és el sant grial per viure aquí. El necessites per a tot.',
    'guide.nie.step1': 'La Caça de la Cita Prèvia',
    'guide.nie.step1_desc': 'La part més difícil. Nosaltres mirem els buits oficials per tu.',
    'guide.nie.btn_cita': 'Veure Buits Oficials',
    'guide.nie.step2': 'El Formulari EX-15',
    'guide.nie.step2_desc': 'Omple\'l perfecte. Posar "Interès Social" o "Treball" acostuma a funcionar.',
    'guide.nie.btn_ex15': 'Descarregar EX-15',
    'guide.nie.step3': 'La Taxa (790-012)',
    'guide.nie.step3_desc': 'Paga els pocs euros que val en un caixer abans d\'anar-hi.',
    'guide.nie.btn_tasa': 'Formulari 790-012',
    'guide.nie.step4': 'El Cara a Cara',
    'guide.nie.step4_desc': '2 còpies de tot. Passaport. Justificant de pagament. I un somriure.',
    'guide.house.title': 'Habitatge i Lloguer',
    'guide.house.desc': 'El mercat vola. Aquí tens com anar un pas per davant.',
    'guide.house.step1': 'Tria el teu Barri',
    'guide.house.step1_desc': 'Gràcia per l\'ambient, Eixample per l\'ordre, Poble Sec per les canyes.',
    'guide.house.step2': 'Eines Pro',
    'guide.house.step2_desc': 'Idealista per a pisos, Badi per a habitacions. Sigues ràpid.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'Prepara el Paperam',
    'guide.house.step3_desc': 'Contracte, nòmines, NIE. Tingues-ho tot en un PDF a punt per enviar.',
    'guide.house.step4': 'Mai Paguis Sense Veure-ho',
    'guide.house.step4_desc': 'Les estafes existeixen. Ni un euro fins que tinguis les claus.',
    'home.news.title': 'EL BUTLLETÍ DEL DIUMENGE',
    'home.news.desc': 'El resum de tot el que realment ha passat a la ciutat aquesta setmana.',
    'home.news.placeholder': 'El teu correu electrònic',
    'home.news.btn': 'REBRE EL BUTLLETÍ',
    'home.contact.title': 'CONECTA',
    'home.contact.desc': 'Tens una idea? Un projecte? Responem en 24 hores.',
    'home.contact.name': 'El teu Nom',
    'home.contact.email': 'Correu Electrònic',
    'home.contact.msg': 'Què ens vols explicar?',
    'home.contact.btn': 'ENVIAR',
    'guide.trans.title': 'Guia de Trànsit',
    'guide.trans.desc': 'Una de les millors xarxes d\'Europa, si saps quines línies esquivar.',
    'guide.trans.step1': 'T-Mobilitat Digital',
    'guide.trans.step1_desc': 'Oblida el paper. Passa\'t al digital amb l\'app.',
    'guide.trans.btn_app': 'Baixar T-Mobilitat',
    'guide.trans.step2': 'La T-Usual mana',
    'guide.trans.step2_desc': 'Viatges il·limitats. Si vius aquí, és l\'únic que necessites.',
    'guide.trans.step3': 'Ull a les teves coses',
    'guide.trans.step3_desc': 'La L3 i L4 són territori comanxe per despistats. Motxilla davant.',
    'guide.trans.step4': 'Mapes del Metro',
    'guide.trans.step4_desc': 'Mapes offline per quan et quedis sense cobertura a sota.',
    'guide.trans.btn_map': 'Descarregar Mapa',
    'guide.empadronamiento.title': 'El Padró',
    'guide.empadronamiento.desc': 'El registre municipal. Vital per la sanitat i l\'administració.',
    'guide.sim.title': 'SIM i Dades',
    'guide.sim.desc': 'Connectivitat total. Les millors xarxes locals per nòmades.',
    'guide.insurance.title': 'Assegurança Mèdica',
    'guide.insurance.desc': 'CatSalut vs Privat. Com anar al metge sense esperes.',
    'guide.bank.title': 'Banca',
    'guide.bank.desc': 'IBANs i com evitar que et clavin comissions de manteniment.',
    'guide.health.title': 'El Hack de la Salut',
    'guide.health.desc': 'Trobar el teu CAP i dominar el portal online.',
    'guide.empadronamiento.step1': 'Reserva la teva OAC', 'guide.empadronamiento.step1_desc': 'Demana cita a l\'oficina d\'atenció ciutadana més propera.',
    'guide.empadronamiento.step2': 'El Contracte', 'guide.empadronamiento.step2_desc': 'Necessites un contracte de lloguer de més de 6 mesos.',
    'guide.empadronamiento.step3': 'El Volant', 'guide.empadronamiento.step3_desc': 'Surt amb el teu paper de resident a l\'instant.',
    'guide.sim.step1': 'Tria Operador', 'guide.sim.step1_desc': 'Digi per preu; Orange o Vodafone per velocitat 5G.',
    'guide.sim.step2': 'Prepago Primer', 'guide.sim.step2_desc': 'Aconsegueix una SIM de prepagament amb passaport mentre esperes el NIE.',
    'guide.sim.step3': 'Locutoris', 'guide.sim.step3_desc': 'El secret per activació instantània a qualsevol barri.',
    'guide.insurance.step1': 'CatSalut (Públic)', 'guide.insurance.step1_desc': 'Gratis. Requereix Padró i número de la seguretat social.',
    'guide.insurance.step2': 'Privat (Adeslas/Sanitas)', 'guide.insurance.step2_desc': 'Crucial per especialistes ràpids i visats de residència.',
    'guide.insurance.step3': 'Sense Copagaments', 'guide.insurance.step3_desc': 'La clàusula "Sense Copagaments" és obligatòria per la majoria de visats.',
    'guide.bank.step1': 'Neobancs Digitals', 'guide.bank.step1_desc': 'N26 i Revolut et donen IBAN espanyol només amb el passaport.',
    'guide.bank.step2': 'Gegants Tradicionals', 'guide.bank.step2_desc': 'Santander o BBVA. Millor si busques hipoteca més endavant.',
    'guide.bank.step3': 'La Trampa de les Comissions', 'guide.bank.step3_desc': 'Demana sempre "Compte Sense Comissions". Mai paguis pel bàsic.',
    'guide.health.step1': 'Ubica el teu CAP', 'guide.health.step1_desc': 'Cada barri té el seu centre de salut. Troba el teu.',
    'guide.health.step2': 'Registra la teva TSI', 'guide.health.step2_desc': 'Porta el padró al CAP perquè et donin la targeta física.',
    'guide.health.step3': 'App La Meva Salut', 'guide.health.step3_desc': 'El portal online per receptes i cites ràpides.',
    'cookie.title': 'Privacitat i Cafè', 'cookie.desc': 'Fem servir cookies per mantenir això en marxa. Les essencials es queden, la resta les pots engegar a pastar fang.', 
    'cookie.accept': 'Acceptar Tot', 'cookie.decline': 'Només Essencials',
    'news.success': 'Ja ets a dins. Benvingut al cercle.', 'news.error.exists': 'Ja ets a la llista, amic.', 'news.error.invalid': 'Aquest correu no em quadra.', 'news.error.generic': 'El servidor s\'ha anat a fer la migdiada. Torna-ho a provar.', 'news.error.server_error': 'La base de dades ha caigut. Hi estem treballant.',
    'news.unsub.success': 'Eliminat. Ens veiem per aquí!'
  },
  DE: {
    'nav.events': 'Events', 'nav.map': 'Stadtplan', 'nav.guide': 'Leitfaden', 'nav.news': 'News', 'nav.about': 'Kontakt',
    'news.today': 'FRISCH VON DER STRASSE',
    'hero.title1': 'Erlebe Barcelona ', 'hero.title2': 'Als Insider.',
    'hero.subtitle': 'Direkter Zugriff auf den Puls der Stadt. Automatisierte Events, geheime Bier-Locations und die ungeschönte Wahrheit über die Bürokratie.',
    'hero.btn1': 'PULS CHECKEN', 'hero.btn2': 'BIERKARTE HIER',
    'feat.event.title': 'Stadtpuls', 'feat.event.desc': 'Handverlesene Events und Live-Feeds von dem, was wirklich in der Stadt passiert.',
    'feat.map.title': 'Die Bierkarte', 'feat.map.desc': 'Der definitive Guide zu Terrassenpreisen und authentischen Lokalen in jedem Viertel.',
    'feat.guide.title': 'Überlebenshilfe', 'feat.guide.desc': 'Alles, was du wirklich wissen musst: Von NIE-Hacks bis zur Wohnungssuche.',
    'footer.desc': 'Die Plattform für uns, die hier leben. Kein Schnickschnack, nur echte Infos.',
    'footer.platform': 'Plattform', 'footer.contact': 'Kontakt', 'footer.rights': 'Alle Rechte vorbehalten.',
    'events.title1': 'Der Puls von ', 'events.title2': 'Barcelona',
    'events.subtitle': 'Kuratierte Schätze & Lokale Geheimnisse',
    'events.desc': 'Aggregiert aus über 50 Quellen: Von RA und Timeout bis hin zu offiziellen Stadtfeeds.',
    'events.category.Music': 'Musik', 'events.category.Art': 'Kunst', 'events.category.Festival': 'Festival', 'events.category.Free': 'Gratis', 'events.category.Opening': 'Eröffnung', 'events.category.Other': 'Sonstiges',
    'events.calendar.title': 'Die Agenda', 'events.venue': 'Ort', 'events.tickets': 'Info', 'events.search': 'Suche deinen Plan...',
    'map.filter.title': 'Filter:', 'map.filter.neighborhood': 'Viertel', 'map.filter.budget': 'Dein Budget (0.5L Bier)',
    'map.filter.facilities': 'Essentials für Residents', 'map.filter.terrace': 'Sonnenterrasse', 'map.filter.sports': 'Live Sport',
    'map.filter.availability': 'Verfügbarkeit', 'map.filter.open': 'Jetzt Offen', 'map.filter.top_rated': 'Favoriten (4.5+ ★)',
    'map.filter.walking_dist': 'Fußweg', 'map.loc.find_me': 'Find mich', 'map.loc.mins': 'Min',
    'map.search.placeholder': 'Suche Bar nach Name...', 'map.results.count': 'Ergebnisse', 'map.venue.beer': 'Bier (0.5L)',
    'map.venue.no_photo': 'Kein Foto', 'map.venue.open_badge': 'OFFEN', 'map.venue.tag.cheap': 'Günstiges Bier',
    'map.venue.loading': 'Lade Straßendaten...', 'map.venue.empty': 'Sackgasse. Probier ein anderes Viertel.', 'map.venue.reset': 'Filter zurücksetzen',
    'map.report_price': 'Preis melden', 'map.directions': 'Route planen', 'map.sun_timeline': 'Sonne auf Terrasse', 'map.verified': 'verifiziert', 'map.confidence.low': 'Keine Preisdaten', 'map.history': 'Preisverlauf',
    'map.form.type': 'Biertyp', 'map.form.size': 'Größe', 'map.form.price': 'Preis (€)', 'map.form.submit': 'Preis senden',
    'review.1': 'Die Bierkarte hat meinen Geldbeutel im Gòtic gerettet! Genial.',
    'review.2': 'Endlich eine Agenda, die auch die kleinen Stadtteilfeste (Fiestas Mayores) zeigt.',
    'review.3': 'Der NIE-Guide ist der einzige Grund, warum ich noch hier bin. Lebensretter.',
    'review.4': 'Unvoreingenommen, vollautomatisch. Das Tool für Residents in BCN.',
    'review.5': 'Ich nutze den Nahverkehr-Guide täglich. T-Mobilitat endlich verständlich!',
    'guide.title1': 'Stadt ', 'guide.title2': 'Leitfaden',
    'guide.desc': 'Schritt-für-Schritt-Anleitungen für Bürokratie und Logistik ohne unnötiges Drama.',
    'guide.nie': 'Hol dir dein NIE, ohne den Verstand zu verlieren.',
    'guide.house': 'Finde dein Zuhause im richtigen Viertel.',
    'guide.trans': 'Meistere Metro, Bus und T-Mobilitat.',
    'guide.read': 'INFO LESEN →',
    'guide.back': 'Zurück zu Guides',
    'guide.nie.title': 'NIE Registrierung',
    'guide.nie.desc': 'Das NIE ist der Schlüssel zum Leben hier. Du brauchst es für absolut alles.',
    'guide.nie.step1': 'Die Cita-Jagd',
    'guide.nie.step1_desc': 'Der schwerste Teil. Wir prüfen offizielle Termine für dich.',
    'guide.nie.btn_cita': 'Termine Prüfen',
    'guide.nie.step2': 'EX-15 Formular',
    'guide.nie.step2_desc': 'Perfekt ausfüllen. "Arbeit" oder "Soziales Interesse" funktioniert meist.',
    'guide.nie.btn_ex15': 'EX-15 Download',
    'guide.nie.step3': 'Die Gebühr (Tasa 790-012)',
    'guide.nie.step3_desc': 'Zahl die paar Euro vorab am Geldautomaten. Bonus: Quittung aufheben.',
    'guide.nie.btn_tasa': 'Formular 790-012',
    'guide.nie.step4': 'Der Termin',
    'guide.nie.step4_desc': '2 Kopien von allem. Reisepass. Beleg. Und ein Lächeln.',
    'guide.house.title': 'Wohnen & Miete',
    'guide.house.desc': 'Der Markt ist extrem schnell. So bleibst du einen Schritt voraus.',
    'guide.house.step1': 'Wähle dein Viertel',
    'guide.house.step1_desc': 'Gràcia für Vibe, Eixample für Ordnung, Poble Sec für kühles Bier.',
    'guide.house.step2': 'Die Profi-Tools',
    'guide.house.step2_desc': 'Idealista für Wohnungen, Badi für Zimmer. Sei schnell.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'Papierkram vorab',
    'guide.house.step3_desc': 'Vertrag, Gehaltsnachweise, NIE. Alles in einem PDF bereithalten.',
    'guide.house.step4': 'Zahle nichts vorab',
    'guide.house.step4_desc': 'Scams are real. Kein Euro, bis du die Schlüssel hast.',
    'home.news.title': 'DER INSIDER-BRIEF',
    'home.news.desc': 'Die sonntägliche Zusammenfassung von allem, was wirklich wichtig war.',
    'home.news.placeholder': 'Deine E-Mail-Adresse',
    'home.news.btn': 'INFOS ERHALTEN',
    'home.contact.title': 'KONTAKT',
    'home.contact.desc': 'Hast du einen Tipp? Eine Idee? Wir antworten binnen 24h.',
    'home.contact.name': 'Dein Name',
    'home.contact.email': 'E-Mail',
    'home.contact.msg': 'Was gibt\'s Neues?',
    'home.contact.btn': 'SENDEN',
    'guide.trans.title': 'Nahverkehr-Infos',
    'guide.trans.desc': 'Eines der besten Netze Europas, wenn man weiß, welche Linien man meidet.',
    'guide.trans.step1': 'Digitale T-Mobilitat',
    'guide.trans.step1_desc': 'Vergiss das Papier. Geh digital mit der App.',
    'guide.trans.btn_app': 'App Laden',
    'guide.trans.step2': 'T-Usual ist Pflicht',
    'guide.trans.step2_desc': 'Unbegrenzte Fahrten. Wenn du hier lebst, die einzig sinnvolle Wahl.',
    'guide.trans.step3': 'Augen auf die Tasche',
    'guide.trans.step3_desc': 'L3 und L4 sind Hotspots für Taschendiebe. Rucksack nach vorne.',
    'guide.trans.step4': 'Metro-Netzplan',
    'guide.trans.step4_desc': 'Offline-Karten für den Moment, wenn das Netz im Tunnel weg ist.',
    'guide.trans.btn_map': 'Netzplan laden',
    'guide.empadronamiento.title': 'Das Padrón',
    'guide.empadronamiento.desc': 'Die Anmeldung im Rathaus. Überlebenswichtig für Gesundheit & Ämter.',
    'guide.sim.title': 'SIM & Daten',
    'guide.sim.desc': 'Top vernetzt. Die besten lokalen Netze für Nomaden.',
    'guide.insurance.title': 'Gesundheits-Check',
    'guide.insurance.desc': 'CatSalut vs. Privat. Wie du ohne Wartezeit zum Arzt kommst.',
    'guide.bank.title': 'Banken-Hacks',
    'guide.bank.desc': 'IBANs und wie du die fiesen Kontoführungsgebühren umgehst.',
    'guide.health.title': 'Gesundheitssystem',
    'guide.health.desc': 'Finde dein CAP und unterwerfe die Online-Portale.',
    'guide.empadronamiento.step1': 'Termin buchen', 'guide.empadronamiento.step1_desc': 'Reservier einen Slot bei deinem nächsten OAC (City Hall).',
    'guide.empadronamiento.step2': 'Der Vertrag', 'guide.empadronamiento.step2_desc': 'Du brauchst einen Mietvertrag über min. 6 Monate.',
    'guide.empadronamiento.step3': 'Das Volante', 'guide.empadronamiento.step3_desc': 'Verlass das Amt direkt mit deinem Resident-Nachweis.',
    'guide.sim.step1': 'Anbieter wählen', 'guide.sim.step1_desc': 'Digi für Preis; Orange oder Vodafone für 5G Speed.',
    'guide.sim.step2': 'Prepaid zuerst', 'guide.sim.step2_desc': 'Hol dir eine Prepaid-SIM nur mit Reisepass, während du aufs NIE wartest.',
    'guide.sim.step3': 'Locutorios', 'guide.sim.step3_desc': 'Das Geheimnis für sofortige Aktivierung in jedem Viertel.',
    'guide.insurance.step1': 'CatSalut (Öffentlich)', 'guide.insurance.step1_desc': 'Gratis. Erfordert Padrón und eine Sozialversicherungsnummer.',
    'guide.insurance.step2': 'Privat (Sanitas/Adeslas)', 'guide.insurance.step2_desc': 'Wichtig für schnelle Fachärzte und Resident-Visa.',
    'guide.insurance.step3': 'Ohne Zuzahlung', 'guide.insurance.step3_desc': 'Die "Sin Copagos" Klausel ist für die meisten Visa Pflicht.',
    'guide.bank.step1': 'Digitale Neo-Banken', 'guide.bank.step1_desc': 'N26 und Revolut bieten spanische IBANs nur mit Reisepass.',
    'guide.bank.step2': 'Traditionelle Größen', 'guide.bank.step2_desc': 'Santander oder BBVA. Besser, falls du später eine Hypothek willst.',
    'guide.bank.step3': 'Die Gebührenfalle', 'guide.bank.step3_desc': 'Frag immer nach "Cuenta Sin Comisiones". Zahl nicht für Basics.',
    'guide.health.step1': 'Finde dein CAP', 'guide.health.step1_desc': 'Jedes Viertel hat sein Gesundheitszentrum. Finde deins.',
    'guide.health.step2': 'Hol dir die TSI', 'guide.health.step2_desc': 'Bring dein Padrón zum CAP für deine physische Karte.',
    'guide.health.step3': 'La Meva Salut App', 'guide.health.step3_desc': 'Das Online-Portal für Rezepte und schnelle Termine.',
    'cookie.title': 'Privatsphäre & Kaffee', 'cookie.desc': 'Wir nutzen Cookies, um den Laden am Laufen zu halten. Essentials bleiben, der Rest ist optional.', 
    'cookie.accept': 'Alle akzeptieren', 'cookie.decline': 'Nur Essentials',
    'news.success': 'Du bist dabei. Willkommen im Zirkel.', 'news.error.exists': 'Du stehst schon auf der Liste.', 'news.error.invalid': 'Die Mail-Adresse passt nicht.', 'news.error.generic': 'Server machen Siesta. Probier\'s später.', 'news.error.server_error': 'Datenbank ist down. Wir sind dran.',
    'news.unsub.success': 'Abgemeldet. Man sieht sich!'
  },
  FR: {
    'nav.events': 'Événements', 'nav.map': 'La Carte', 'nav.guide': 'Le Guide', 'nav.news': 'Infos', 'nav.about': 'Contact',
    'news.today': 'EN DIRECT DE LA RUE',
    'hero.title1': 'Vivez Barcelone ', 'hero.title2': 'Comme un Insider.',
    'hero.subtitle': 'Accès sans filtre au pouls de la ville. Événements automatisés, bars secrets et la vérité brute sur la bureaucratie.',
    'hero.btn1': 'VOIR LE POULS', 'hero.btn2': 'CARTE DES BIÈRES',
    'feat.event.title': 'Pulsations', 'feat.event.desc': 'Événements triés sur le volet et flux en direct de ce qui se passe vraiment.',
    'feat.map.title': 'La Carte des Bières', 'feat.map.desc': 'Le guide définitif des prix en terrasse et des spots authentiques par quartier.',
    'feat.guide.title': 'Guides de Survie', 'feat.guide.desc': 'Tout ce qu\'il faut savoir : des astuces NIE à la quête d\'un appartement.',
    'footer.desc': 'La plateforme pour ceux qui vivent ici. Pas de blabla, juste de l\'info utile.',
    'footer.platform': 'Plateforme', 'footer.contact': 'Contact', 'footer.rights': 'Tous droits réservés.',
    'events.title1': 'Le Pouls de ', 'events.title2': 'Barcelone',
    'events.subtitle': 'Pépites Curieuses & Secrets Locaux',
    'events.desc': 'Données agrégées de 50+ sources : de RA et Timeout aux flux de la Mairie.',
    'events.category.Music': 'Musique', 'events.category.Art': 'Art', 'events.category.Festival': 'Festival', 'events.category.Free': 'Gratuit', 'events.category.Opening': 'Vernissage', 'events.category.Other': 'Autres',
    'events.calendar.title': 'L\'Agenda', 'events.venue': 'Lieu', 'events.tickets': 'Infos', 'events.search': 'Chercher un plan...',
    'map.filter.title': 'Filtres :', 'map.filter.neighborhood': 'Quartier', 'map.filter.budget': 'Votre budget (Bière 0.5L)',
    'map.filter.facilities': 'Essentiels Résidents', 'map.filter.terrace': 'Terrasse au Soleil', 'map.filter.sports': 'Sport en Direct',
    'map.filter.availability': 'Disponibilité', 'map.filter.open': 'Ouvert Maintenant', 'map.filter.top_rated': 'Favoris (4.5+ ★)',
    'map.filter.walking_dist': 'À pied', 'map.loc.find_me': 'Trouve-moi', 'map.loc.mins': 'min',
    'map.search.placeholder': 'Chercher un bar par nom...', 'map.results.count': 'résultats', 'map.venue.beer': 'Bière (0.5L)',
    'map.venue.no_photo': 'Sans Photo', 'map.venue.open_badge': 'OUVERT', 'map.venue.tag.cheap': 'Bière pas chère',
    'map.venue.loading': 'Chargement des données...', 'map.venue.empty': 'Impasse. Essayez un autre quartier.', 'map.venue.reset': 'Réinitialiser',
    'map.report_price': 'Signaler prix', 'map.directions': 'Itinéraire', 'map.sun_timeline': 'Soleil terrasse', 'map.verified': 'vérifié', 'map.confidence.low': 'Pas de prix encore', 'map.history': 'Historique',
    'map.form.type': 'Type de bière', 'map.form.size': 'Taille', 'map.form.price': 'Prix (€)', 'map.form.submit': 'Envoyer prix',
    'review.1': 'La carte des bières a sauvé mon portefeuille au Gòtic ! Génial.',
    'review.2': 'Enfin un agenda qui inclut les fêtes de quartier (Fiestas Mayores).',
    'review.3': 'Le guide NIE est la seule raison pour laquelle je suis encore là.',
    'review.4': 'Sans filtre, automatisé. L\'outil parfait pour les résidents à BCN.',
    'review.5': 'J\'utilise le guide transport tous les jours. La T-Mobilitat enfin simple !',
    'guide.title1': 'Guides de ', 'guide.title2': 'Rue',
    'guide.desc': 'Instructions étape par étape pour naviguer dans la bureaucratie sans drame.',
    'guide.nie': 'Obtenez votre NIE sans perdre la tête.',
    'guide.house': 'Trouvez votre chez-vous dans le bon quartier.',
    'guide.trans': 'Maîtrisez le métro, le bus et la T-Mobilitat.',
    'guide.read': 'LIRE L\'INFO →',
    'guide.back': 'Retour aux Guides',
    'guide.nie.title': 'Enregistrement NIE',
    'guide.nie.desc': 'Le NIE est le sésame pour vivre ici. Requis pour absolument tout.',
    'guide.nie.step1': 'La Chasse à la Cita',
    'guide.nie.step1_desc': 'Le plus dur. Nous surveillons les créneaux officiels pour vous.',
    'guide.nie.btn_cita': 'Voir les Créneaux',
    'guide.nie.step2': 'Formulaire EX-15',
    'guide.nie.step2_desc': 'À remplir parfaitement. "Travail" ou "Intérêt Social" passe souvent.',
    'guide.nie.btn_ex15': 'Télécharger EX-15',
    'guide.nie.step3': 'La Taxe (Tasa 790-012)',
    'guide.nie.step3_desc': 'Payez les quelques euros au guichet auto avant le rdv.',
    'guide.nie.btn_tasa': 'Formulaire 790-012',
    'guide.nie.step4': 'Le Face-à-Face',
    'guide.nie.step4_desc': '2 copies de tout. Passeport. Reçu de paiement. Et un sourire.',
    'guide.house.title': 'Logement & Loyer',
    'guide.house.desc': 'Le marché vole. Voici comment garder une longueur d\'avance.',
    'guide.house.step1': 'Choisissez votre Barrio',
    'guide.house.step1_desc': 'Gràcia pour l\'ambiance, Eixample pour l\'ordre, Poble Sec pour la bière.',
    'guide.house.step2': 'Les Outils Pro',
    'guide.house.step2_desc': 'Idealista pour les apparts, Badi pour les chambres. Soyez rapide.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'Dossier Prêt',
    'guide.house.step3_desc': 'Contrat, fiches de paie, NIE. Tout dans un seul PDF.',
    'guide.house.step4': 'Ne Payez Rien d\'Avance',
    'guide.house.step4_desc': 'Les arnaques existent. Pas un euro avant d\'avoir les clés.',
    'home.news.title': 'LE BRIEF DES INSIDERS',
    'home.news.desc': 'Le récap du dimanche de tout ce qui s\'est vraiment passé en ville.',
    'home.news.placeholder': 'Votre adresse e-mail',
    'home.news.btn': 'RECEVOIR L\'INFO',
    'home.contact.title': 'CONNECTER',
    'home.contact.desc': 'Un tuyau ? Une idée ? On répond sous 24h.',
    'home.contact.name': 'Votre Nom',
    'home.contact.email': 'E-mail',
    'home.contact.msg': 'Quoi de neuf ?',
    'home.contact.btn': 'ENVOYER',
    'guide.trans.title': 'Infos Transit',
    'guide.trans.desc': 'L\'un des meilleurs réseaux d\'Europe, si on sait quelles lignes éviter.',
    'guide.trans.step1': 'T-Mobilitat Digitale',
    'guide.trans.step1_desc': 'Oubliez la carte papier. Passez au digital via l\'app.',
    'guide.trans.btn_app': 'Charger l\'App',
    'guide.trans.step2': 'T-Usual est Roi',
    'guide.trans.step2_desc': 'Trajets illimités. Si vous vivez ici, c\'est le seul choix logique.',
    'guide.trans.step3': 'Œil sur vos Affaires',
    'guide.trans.step3_desc': 'Les lignes L3 et L4 sont prisées par les pickpockets. Sac devant.',
    'guide.trans.step4': 'Plan du Métro',
    'guide.trans.step4_desc': 'Plans offline pour quand vous perdez le réseau sous terre.',
    'guide.trans.btn_map': 'Télécharger le Plan',
    'guide.empadronamiento.title': 'Le Padrón',
    'guide.empadronamiento.desc': 'L\'inscription à la mairie. Vital pour la santé & l\'administration.',
    'guide.sim.title': 'SIM & Data',
    'guide.sim.desc': 'Connectivité totale. Les meilleurs réseaux locaux pour nomades.',
    'guide.insurance.title': 'Infos Santé',
    'guide.insurance.desc': 'CatSalut vs Privé. Comment voir un médecin sans attendre.',
    'guide.bank.title': 'Hacks Bancaires',
    'guide.bank.desc': 'IBANs et comment éviter les frais de tenue de compte abusifs.',
    'guide.health.title': 'Système de Santé',
    'guide.health.desc': 'Trouvez votre CAP et maîtrisez les portails en ligne.',
    'guide.empadronamiento.step1': 'Réserver un Créneau', 'guide.empadronamiento.step1_desc': 'Demandez un rdv à la mairie (OAC) la plus proche.',
    'guide.empadronamiento.step2': 'Le Contrat', 'guide.empadronamiento.step2_desc': 'Il vous faut un contrat de location de 6 mois minimum.',
    'guide.empadronamiento.step3': 'Le Volante', 'guide.empadronamiento.step3_desc': 'Récupérez votre justificatif de résidence instantanément.',
    'guide.sim.step1': 'Choisir l\'Opérateur', 'guide.sim.step1_desc': 'Digi pour le prix ; Orange ou Vodafone pour la 5G.',
    'guide.sim.step2': 'Prépayé d\'Abord', 'guide.sim.step2_desc': 'Prenez une SIM prépayée avec passeport en attendant le NIE.',
    'guide.sim.step3': 'Locutorios', 'guide.sim.step3_desc': 'Le secret pour une activation immédiate dans n\'importe quel quartier.',
    'guide.insurance.step1': 'CatSalut (Public)', 'guide.insurance.step1_desc': 'Gratuit. Requis : Padrón et numéro de sécu espagnol.',
    'guide.insurance.step2': 'Privé (Sanitas/Adeslas)', 'guide.insurance.step2_desc': 'Crucial pour les spécialistes et les visas de résidence.',
    'guide.insurance.step3': 'Sans Avance (Copagos)', 'guide.insurance.step3_desc': 'La clause "Sin Copagos" est obligatoire pour la plupart des visas.',
    'guide.bank.step1': 'Néobanques Digitales', 'guide.bank.step1_desc': 'N26 et Revolut ouvrent un IBAN espagnol avec juste le passeport.',
    'guide.bank.step2': 'Géants Traditionnels', 'guide.bank.step2_desc': 'Santander ou BBVA. Mieux si vous visez un prêt immo plus tard.',
    'guide.bank.step3': 'Le Piège des Frais', 'guide.bank.step3_desc': 'Cherchez "Cuenta Sin Comisiones". Ne payez pas pour les bases.',
    'guide.health.step1': 'Trouvez votre CAP', 'guide.health.step1_desc': 'Chaque quartier a son centre de santé. Localisez le vôtre.',
    'guide.health.step2': 'Obtenez la TSI', 'guide.health.step2_desc': 'Apportez votre Padrón au CAP pour votre carte physique.',
    'guide.health.step3': 'App La Meva Salut', 'guide.health.step3_desc': 'Le portail en ligne pour ordonnances et rdv rapides.',
    'cookie.title': 'Respect & Café', 'cookie.desc': 'On utilise des cookies pour faire tourner le site. Les essentiels restent, les autres sont optionnels.', 
    'cookie.accept': 'Accepter Tout', 'cookie.decline': 'Essentiels Uniquement',
    'news.success': 'C\'est fait. Bienvenue dans le cercle.', 'news.error.exists': 'Déjà inscrit, l\'ami.', 'news.error.invalid': 'E-mail non valide.', 'news.error.generic': 'Serveur en sieste. Réessayez plus tard.', 'news.error.server_error': 'BDD HS. On est dessus.',
    'news.unsub.success': 'Désinscrit. À la prochaine !'
  },

  NL: {
    'nav.events': 'Events', 'nav.map': 'De Kaart', 'nav.guide': 'De Gids', 'nav.news': 'Nieuws', 'nav.about': 'Contact',
    'news.today': 'VERS VAN DE STRAAT',
    'hero.title1': 'Beleef Barcelona ', 'hero.title2': 'Als Insider.',
    'hero.subtitle': 'Directe toegang tot de hartslag van de stad. Geautomatiseerde events, verborgen bar-locaties en de rauwe waarheid over de bureaucratie.',
    'hero.btn1': 'BEKIJK DE PULSE', 'hero.btn2': 'BIERKAART HIER',
    'feat.event.title': 'Stadspuls', 'feat.event.desc': 'Handgeplukte events en live feeds van wat er écht gebeurt in de stad.',
    'feat.map.title': 'De Bierkaart', 'feat.map.desc': 'De definitieve gids voor terrasprijzen en authentieke spots in elke buurt.',
    'feat.guide.title': 'Survival Gidsen', 'feat.guide.desc': 'Alles wat je echt moet weten: van NIE-hacks tot het vinden van een woning.',
    'footer.desc': 'Hét platform voor ons die hier wonen. Geen poespas, alleen de beste info.',
    'footer.platform': 'Platform', 'footer.contact': 'Contact', 'footer.rights': 'Alle rechten voorbehouden.',
    'events.title1': 'De Pulse van ', 'events.title2': 'Barcelona',
    'events.subtitle': 'Gecureerde Parels & Lokale Geheimen',
    'events.desc': 'Geaggregeerd uit 50+ bronnen: van RA en Timeout tot officiële gemeente-feeds.',
    'events.category.Music': 'Muziek', 'events.category.Art': 'Kunst', 'events.category.Festival': 'Festival', 'events.category.Free': 'Gratis', 'events.category.Opening': 'Opening', 'events.category.Other': 'Overig',
    'events.calendar.title': 'De Agenda', 'events.venue': 'Locatie', 'events.tickets': 'Info', 'events.search': 'Zoek jouw plan...',
    'map.filter.title': 'Filters:', 'map.filter.neighborhood': 'Buurt', 'map.filter.budget': 'Jouw budget (0.5L Bier)',
    'map.filter.facilities': 'Essentials voor Residents', 'map.filter.terrace': 'Zonneterras', 'map.filter.sports': 'Live Sport',
    'map.filter.availability': 'Beschikbaarheid', 'map.filter.open': 'Nu Open', 'map.filter.top_rated': 'Favorieten (4.5+ ★)',
    'map.filter.walking_dist': 'Loopafstand', 'map.loc.find_me': 'Vind mij', 'map.loc.mins': 'min',
    'map.search.placeholder': 'Zoek bar op naam...', 'map.results.count': 'resultaten', 'map.venue.beer': 'Bier (0.5L)',
    'map.venue.no_photo': 'Geen Foto', 'map.venue.open_badge': 'OPEN', 'map.venue.tag.cheap': 'Goedkoop bier',
    'map.venue.loading': 'Straatdata laden...', 'map.venue.empty': 'Doodlopend spoor. Probeer een andere buurt.', 'map.venue.reset': 'Filters resetten',
    'map.report_price': 'Prijs melden', 'map.directions': 'Routebeschrijving', 'map.sun_timeline': 'Zon op terras', 'map.verified': 'geverifieerd', 'map.confidence.low': 'Nog geen prijsdata', 'map.history': 'Prijsverloop',
    'map.form.type': 'Biertype', 'map.form.size': 'Grootte', 'map.form.price': 'Prijs (€)', 'map.form.submit': 'Prijs opslaan',
    'review.1': 'De bierkaart heeft mijn portemonnee gered in Gòtic! Geniaal.',
    'review.2': 'Eindelijk een agenda die ook de wijksfestivals (Fiestas Mayores) toont.',
    'review.3': 'De NIE-gids is de enige reden dat ik hier nog ben. Lifesaver.',
    'review.4': 'Onbevooroordeeld, volautomatisch. Dé tool voor residents in BCN.',
    'review.5': 'Ik gebruik de vervoersgids dagelijks. T-Mobilitat eindelijk duidelijk!',
    'guide.title1': 'Straat ', 'guide.title2': 'Gidsen',
    'guide.desc': 'Stapsgewijze instructies voor bureaucratie en logistiek zonder het drama.',
    'guide.nie': 'Krijg je NIE zonder gek te worden.',
    'guide.house': 'Vind je plek in de juiste buurt.',
    'guide.trans': 'Beheers de metro, bus en T-Mobilitat.',
    'guide.read': 'LEES DE INTEL →',
    'guide.back': 'Terug naar Gidsen',
    'guide.nie.title': 'NIE Registratie',
    'guide.nie.desc': 'De NIE is de heilige graal van het wonen hier. Je hebt het voor alles nodig.',
    'guide.nie.step1': 'De Cita-jacht',
    'guide.nie.step1_desc': 'Het moeilijkste deel. Wij checken officiële tijdsloten voor je.',
    'guide.nie.btn_cita': 'Check Tijdsloten',
    'guide.nie.step2': 'EX-15 Papierwerk',
    'guide.nie.step2_desc': 'Perfect invullen. "Werk" of "Sociaal Belang" werkt meestal.',
    'guide.nie.btn_ex15': 'Download EX-15',
    'guide.nie.step3': 'De Tasa Fee (790-012)',
    'guide.nie.step3_desc': 'Betaal de paar euro bij een pinautomaat vóór je afspraak.',
    'guide.nie.btn_tasa': 'Formulier 790-012',
    'guide.nie.step4': 'Het Gesprek',
    'guide.nie.step4_desc': '2 kopieën van alles. Paspoort. Betaalbewijs. En een glimlach.',
    'guide.house.title': 'Wonen & Huur',
    'guide.house.desc': 'De markt gaat razendsnel. Zo blijf je een stap voor.',
    'guide.house.step1': 'Kies je Barrio',
    'guide.house.step1_desc': 'Gràcia voor de sfeer, Eixample voor orde, Poble Sec voor bier.',
    'guide.house.step2': 'De Pro Tools',
    'guide.house.step2_desc': 'Idealista en Badi zijn de tools die je nodig hebt. Wees snel.',
    'guide.house.btn_idealista': 'Idealista', 'guide.house.btn_badi': 'Badi',
    'guide.house.step3': 'Papierwerk Klaar',
    'guide.house.step3_desc': 'Contract, loonstroken, NIE. Alles in één PDF klaarzetten.',
    'guide.house.step4': 'Betaal Niets Vooraf',
    'guide.house.step4_desc': 'Scams zijn echt. Geen euro totdat je de sleutels hebt.',
    'home.news.title': 'DE INSIDER-BRIEF',
    'home.news.desc': 'De zondagse recap van alles wat er écht gebeurde in de stad.',
    'home.news.placeholder': 'Jouw e-mailadres',
    'home.news.btn': 'KRIJG DE INTEL',
    'home.contact.title': 'CONTACT',
    'home.contact.desc': 'Heb je een tip? Een idee? We reageren binnen 24u.',
    'home.contact.name': 'Jouw Naam',
    'home.contact.email': 'E-mailadres',
    'home.contact.msg': 'Wat is er gaande?',
    'home.contact.btn': 'VERSTUREN',
    'guide.trans.title': 'Vervoer-Intel',
    'guide.trans.desc': 'Een van de beste netwerken van Europa, als je weet welke lijnen je moet mijden.',
    'guide.trans.step1': 'Digitale T-Mobilitat',
    'guide.trans.step1_desc': 'Vergeet de papieren kaart. Ga digitaal via de app.',
    'guide.trans.btn_app': 'Download de App',
    'guide.trans.step2': 'T-Usual is Heilig',
    'guide.trans.step2_desc': 'Onbeperkt reizen. Als je hier woont, de enige logische keuze.',
    'guide.trans.step3': 'Let op je Spullen',
    'guide.trans.step3_desc': 'L3 en L4 zijn hotspots for zakkenrollers. Rugzak naar voren.',
    'guide.trans.step4': 'Metrokaart',
    'guide.trans.step4_desc': 'Offline kaarten voor als je bereik verliest onder de grond.',
    'guide.trans.btn_map': 'Download Kaart',
    'guide.empadronamiento.title': 'De Padrón',
    'guide.empadronamiento.desc': 'De inschrijving bij de gemeente. Cruciaal voor zorg & administratie.',
    'guide.sim.title': 'SIM & Data',
    'guide.sim.desc': 'Altijd verbonden. De beste lokale netwerken voor nomaden.',
    'guide.insurance.title': 'Zorg-Intel',
    'guide.insurance.desc': 'CatSalut vs. Privé. Hoe je een dokter ziet zonder wachtlijst.',
    'guide.bank.title': 'Banken-hacks',
    'guide.bank.desc': 'IBANs en hoe je die irritante beheerkosten ontwijkt.',
    'guide.health.title': 'Gezondheidszorg',
    'guide.health.desc': 'Vind je CAP en overmeester de online portals.',
    'guide.empadronamiento.step1': 'Boek je Afspraak', 'guide.empadronamiento.step1_desc': 'Vraag een slot aan bij je dichtstbijzijnde OAC (City Hall).',
    'guide.empadronamiento.step2': 'Het Contract', 'guide.empadronamiento.step2_desc': 'Je hebt een huurcontract van min. 6 maanden nodig.',
    'guide.empadronamiento.step3': 'De Volante', 'guide.empadronamiento.step3_desc': 'Loop direct naar buiten met je bewijs van inschrijving.',
    'guide.sim.step1': 'Kies een Netwerk', 'guide.sim.step1_desc': 'Digi voor waarde; Orange of Vodafone voor 5G speed.',
    'guide.sim.step2': 'Prepaid Eerst', 'guide.sim.step2_desc': 'Koop een prepaid SIM met je paspoort terwijl je op je NIE wacht.',
    'guide.sim.step3': 'Locutorios', 'guide.sim.step3_desc': 'Het geheim voor directe activatie in elke buurt.',
    'guide.insurance.step1': 'CatSalut (Publiek)', 'guide.insurance.step1_desc': 'Gratis. Vereist Padrón en een burgerservicenummer.',
    'guide.insurance.step2': 'Privé (Sanitas/Adeslas)', 'guide.insurance.step2_desc': 'Crucial voor specialisten en verblijfsvisa.',
    'guide.insurance.step3': 'Zonder Eigen Bijdrage', 'guide.insurance.step3_desc': 'De "Sin Copagos" clausule is verplicht voor de meeste visa.',
    'guide.bank.step1': 'Digitale Neo-Banken', 'guide.bank.step1_desc': 'N26 en Revolut geven je een Spaanse IBAN met alleen je paspoort.',
    'guide.bank.step2': 'Grootbanken', 'guide.bank.step2_desc': 'Santander of BBVA. Beter als je later een hypotheek wilt.',
    'guide.bank.step3': 'De Fraudeval', 'guide.bank.step3_desc': 'Zoek altijd naar een "Cuenta Sin Comisiones". Betaal niet voor de basis.',
    'guide.health.step1': 'Vind jouw CAP', 'guide.health.step1_desc': 'Jouw lokale Centro de Atención Primaria is gebaseerd op je adres.',
    'guide.health.step2': 'Krijg de TSI-kaart', 'guide.health.step2_desc': 'Breng je Padrón en ID naar de CAP om je fysiek te registreren.',
    'guide.health.step3': 'La Meva Salut', 'guide.health.step3_desc': 'Via de app boek je de dokter direct in 11 seconden.',
    'cookie.title': 'Privacy & Koffie', 'cookie.desc': 'We gebruiken cookies om de boel draaiende te houden. Essentials blijven, de rest is optioneel.', 
    'cookie.accept': 'Alles Accepteren', 'cookie.decline': 'Alleen Essentials',
    'news.success': 'Je bent binnen. Welkom in de cirkel.', 'news.error.exists': 'Je staat al op de lijst.', 'news.error.invalid': 'Dat e-mailadres klopt niet.', 'news.error.generic': 'Servers doen een siësta. Probeer later.', 'news.error.server_error': 'Database ligt eruit. We werken eraan.',
    'news.unsub.success': 'Afgemeld. Tot ziens!',
    'home.hero.title': 'BARCELONA. NU.',
    'home.hero.subtitle': 'Events · Goedkoop bier · Lokaal nieuws · Gidsen — dagelijks bijgewerkt.',
    'home.hero.cta_events': "Wat is er vanavond te doen →",
    'home.hero.cta_beers': "Vind goedkoop bier →",
    'home.bcn_today': 'BCN VANDAAG',
    'home.more_news': 'Meer nieuws →',
    'home.sunday_briefing': 'DE ZONDAG RECAP',
    'home.sunday_desc': 'Elke zondag. De week in BCN, kort en bondig.',
    'home.subscribe': 'Inschrijven',
    'home.join_count': 'Sluit je aan bij 1.200+ internationals',
    'map.per_half_litre': 'per 0.5L tap',
    'map.reviews': 'beoordelingen',
    'map.verified_price': 'Geverifieerde prijs',
    'map.verified_desc': 'Onlangs bijgewerkt door gebruikers',
    'map.features': 'Kenmerken',
    'map.feature.terrace': 'Terras',
    'map.feature.sports': 'Sportscherm',
    'map.feature.rooftop': 'Rooftop uitzicht',
    'map.sun_outlook': 'Zonverwachting',
    'map.get_directions': 'Routebeschrijving',
    'map.update_price': 'Aanpassen'
  }
};

const LanguageContext = createContext<LangContextArgs>({ lang: 'EN', setLang: () => {}, t: () => '' });

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Lang>('EN');
  useEffect(() => {
    const saved = localStorage.getItem('app_lang') as Lang;
    if (saved && ['EN', 'ES', 'CA', 'DE', 'FR', 'NL'].includes(saved)) setLang(saved);
  }, []);
  const changeLang = (l: Lang) => { setLang(l); localStorage.setItem('app_lang', l); };
  const t = (key: string) => {
    const k = key as keyof typeof translations.EN;
    return translations[lang][k] || key;
  };
  return <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
